// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxCJgkGp7BPtTyetCj8js0wh4u4q9PDk',
    appId: '1:558163087247:web:342b693c398e5e6a7785fa',
    messagingSenderId: '558163087247',
    projectId: 'client-test-78d3e',
    authDomain: 'client-test-78d3e.firebaseapp.com',
    storageBucket: 'client-test-78d3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnv57fJee2uH2DljSG5kfYfF1nAipdMY',
    appId: '1:558163087247:android:1ee996c5606e94877785fa',
    messagingSenderId: '558163087247',
    projectId: 'client-test-78d3e',
    storageBucket: 'client-test-78d3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5vezsLKw9yWhY0ZfCsYnI0FOiS6aGCc',
    appId: '1:558163087247:ios:00858c11d68b5be77785fa',
    messagingSenderId: '558163087247',
    projectId: 'client-test-78d3e',
    storageBucket: 'client-test-78d3e.appspot.com',
    iosBundleId: 'com.example.manageClients',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5vezsLKw9yWhY0ZfCsYnI0FOiS6aGCc',
    appId: '1:558163087247:ios:00858c11d68b5be77785fa',
    messagingSenderId: '558163087247',
    projectId: 'client-test-78d3e',
    storageBucket: 'client-test-78d3e.appspot.com',
    iosBundleId: 'com.example.manageClients',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYxCJgkGp7BPtTyetCj8js0wh4u4q9PDk',
    appId: '1:558163087247:web:e0e8faf5ef2766ed7785fa',
    messagingSenderId: '558163087247',
    projectId: 'client-test-78d3e',
    authDomain: 'client-test-78d3e.firebaseapp.com',
    storageBucket: 'client-test-78d3e.appspot.com',
  );
}
